version: '3.3'
services:
  monghost-redis:
    image: redis:5
    container_name: monghost-redis
    ports:
      - "12179:6379"
    restart: always
    networks:
      - monghost_net

  monghost-mongo:
    image: mongo:4.2
    container_name: monghost-mongo
    ports:
      - "12117:27017"
    restart: always
    networks:
      - monghost_net

networks:
  monghost_net:
    driver: bridge
